[package]
name = "generator"
version = "0.1.0"
authors = ["Daniel Duan <daniel@duan.ca>"]
edition = "2018"

[dependencies]
askama = "=0.14"
chrono = "=0.4"
comrak = { version = "0.14", default-features = false }
regex = "=1.6"
slug = "=0.1"
walkdir = "=2.3"
